services:
    adagi_os:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: adagi_os:latest
        volumes:
            - ./kiosk_os:/home/imagegen/kiosk_os